CREATE TABLE tweets (
                                        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                        user_id integer,
                                        text varchar(250),
                                        datetime date,
                                        created_at date NOT NULL DEFAULT CURRENT_DATE,
                                        last_updated date NOT NULL DEFAULT CURRENT_DATE
                                       );
CREATE TABLE followers (
                                        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                        user_id integer,
                                        user_id_followed integer,
                                        datetime date,
                                        status varchar(50),
                                        created_at date NOT NULL DEFAULT CURRENT_DATE,
                                        last_updated date NOT NULL DEFAULT CURRENT_DATE,
                                        UNIQUE (user_id, user_id_followed,status));
CREATE UNIQUE INDEX ON "followers" ("user_id", "user_id_followed");   